'''
Print all subsequences of a string

Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.
Examples: 

Input : abc
Output : a, b, c, ab, bc, ac, abc

Input : aaa
Output : a, aa, aaa
'''

import itertools

def subsequences(s):
    combs=[]
    for i in range(1,len(s)+1):
        combs.append(list(itertools.combinations(s,i)))
    l2=[]
    for c in combs:
        for t in c:
            l2.append(''.join(t))
    return l2
s=input()
print(subsequences(s))
